/*
 * TextAnalyzerGUI.java
 *
 * Created on Oct 21, 2009, 1:28:12 PM
 */
package textanalyzerapp;

/**
 *
 * @author Alvin Ling
 */
public class TextAnalyzerGUI extends javax.swing.JFrame
{
    private TextAnalyzer ta;

    /** Creates new form TextAnalyzerGUI */
    public TextAnalyzerGUI()
    {
        initComponents();
        setSize(710, 410);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        enterTextLabel = new javax.swing.JLabel();
        inputScrollPane = new javax.swing.JScrollPane();
        inputTextArea = new javax.swing.JTextArea();
        resetButton = new javax.swing.JButton();
        analyzeButton = new javax.swing.JButton();
        wordCountLabel = new javax.swing.JLabel();
        wordCountField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        searchButton = new javax.swing.JButton();
        clickToLabel = new javax.swing.JLabel();
        searchWordlabel = new javax.swing.JLabel();
        searchField = new javax.swing.JTextField();
        frequencyLabel = new javax.swing.JLabel();
        frequencyField = new javax.swing.JTextField();
        charFrequencyField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        histogram = new javax.swing.JTextArea();
        makeHistButton = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 480));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        enterTextLabel.setText("enter text below: ");
        getContentPane().add(enterTextLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        inputTextArea.setColumns(20);
        inputTextArea.setFont(new java.awt.Font("Monospaced", 0, 10));
        inputTextArea.setLineWrap(true);
        inputTextArea.setRows(5);
        inputTextArea.setWrapStyleWord(true);
        inputScrollPane.setViewportView(inputTextArea);

        getContentPane().add(inputScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 350, 170));

        resetButton.setText("reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });
        getContentPane().add(resetButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        analyzeButton.setText("analyze");
        analyzeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analyzeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(analyzeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        wordCountLabel.setText("word count: ");
        getContentPane().add(wordCountLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, -1, -1));

        wordCountField.setEditable(false);
        wordCountField.setFont(new java.awt.Font("Tahoma", 0, 10));
        getContentPane().add(wordCountField, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, 140, -1));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 40, 30, 150));

        searchButton.setText("search");
        searchButton.setEnabled(false);
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        getContentPane().add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 30, -1, -1));

        clickToLabel.setFont(new java.awt.Font("Tahoma", 0, 10));
        clickToLabel.setText("[click analyze to activate button]");
        getContentPane().add(clickToLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 60, -1, -1));

        searchWordlabel.setText("search word: ");
        getContentPane().add(searchWordlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 90, -1, -1));

        searchField.setFont(new java.awt.Font("Tahoma", 0, 10));
        searchField.setEnabled(false);
        searchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFieldActionPerformed(evt);
            }
        });
        getContentPane().add(searchField, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 90, 140, -1));

        frequencyLabel.setText("word frequency: ");
        getContentPane().add(frequencyLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 120, -1, -1));

        frequencyField.setEditable(false);
        frequencyField.setFont(new java.awt.Font("Tahoma", 0, 10));
        frequencyField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frequencyFieldActionPerformed(evt);
            }
        });
        getContentPane().add(frequencyField, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 120, 140, -1));

        charFrequencyField.setEditable(false);
        charFrequencyField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                charFrequencyFieldActionPerformed(evt);
            }
        });
        getContentPane().add(charFrequencyField, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 140, 20));

        jLabel1.setText("character count:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 100, 10));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 850, 10));

        histogram.setColumns(20);
        histogram.setEditable(false);
        histogram.setRows(5);
        jScrollPane2.setViewportView(histogram);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 730, 200));

        makeHistButton.setText("Build Histogram");
        makeHistButton.setEnabled(false);
        makeHistButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makeHistButtonActionPerformed(evt);
            }
        });
        getContentPane().add(makeHistButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 260, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
//        all textFields are set to a null String.  Search button is disabled.  TextAnalyzer object
//        is reset.
//        preCondition: running program
//        postCondition: all fields are set to null and searchButton is disabled.
        inputTextArea.setText("");
        wordCountField.setText("");
        frequencyField.setText("");
        charFrequencyField.setText("");
        searchField.setEnabled(false);
        searchField.setText("");
        searchButton.setEnabled(false);
        makeHistButton.setEnabled(false);
        histogram.setText("");
    }//GEN-LAST:event_resetButtonActionPerformed

    private void analyzeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analyzeButtonActionPerformed

//        text from inputArea is assigned to a local String variable and sent to TextAnalyzer using
//        the _______ method.  The ______method returns the number of words in the String as an int.
//        This int value is then displayed using setText() in the wordCountField.  Search Button is enabled.
//        preCondition:  inputArea contains a nonEmpty String
//        postCondition: int value of words is displayed in wordCountArea
        ta = new TextAnalyzer(inputTextArea.getText());
        wordCountField.setText("" + ta.getCount());
        charFrequencyField.setText("" + ta.getCharCount());
        searchButton.setEnabled(true);
        searchField.setEnabled(true);
        makeHistButton.setEnabled(true);
        searchField.setText("");
        frequencyField.setText("");
    }//GEN-LAST:event_analyzeButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
//        text from searchField is assigned to a local String variable and sent to
//        TextAnalyzer using the _______ method.  The _______ method returns an int
//        representing the  number of times that String occurs in the inputArea.
//        preCondition: analyzeButton has been clicked.  inputArea is non-NULL.
//        postCondition: word frequency is displayed in frequencyField
        frequencyField.setText("" + ta.getSearchCount(searchField.getText()));
    }//GEN-LAST:event_searchButtonActionPerformed

    private void frequencyFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_frequencyFieldActionPerformed
    {//GEN-HEADEREND:event_frequencyFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_frequencyFieldActionPerformed

    private void searchFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_searchFieldActionPerformed
    {//GEN-HEADEREND:event_searchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchFieldActionPerformed

    private void charFrequencyFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_charFrequencyFieldActionPerformed
    {//GEN-HEADEREND:event_charFrequencyFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_charFrequencyFieldActionPerformed

    private void makeHistButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_makeHistButtonActionPerformed
    {//GEN-HEADEREND:event_makeHistButtonActionPerformed
        ta = new TextAnalyzer(inputTextArea.getText());
        histogram.append("Word" + "\t\tFrequency\t\u25A0 = 10\n\n");
        while(ta.hasNextHistEntry())
        {
            histogram.append(ta.nextHistEntry() + "\n");
        }
    }//GEN-LAST:event_makeHistButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        java.awt.EventQueue.invokeLater(new Runnable()
        {

            public void run()
            {
                new TextAnalyzerGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton analyzeButton;
    private javax.swing.JTextField charFrequencyField;
    private javax.swing.JLabel clickToLabel;
    private javax.swing.JLabel enterTextLabel;
    private javax.swing.JTextField frequencyField;
    private javax.swing.JLabel frequencyLabel;
    private javax.swing.JTextArea histogram;
    private javax.swing.JScrollPane inputScrollPane;
    private javax.swing.JTextArea inputTextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton makeHistButton;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchField;
    private javax.swing.JLabel searchWordlabel;
    private javax.swing.JTextField wordCountField;
    private javax.swing.JLabel wordCountLabel;
    // End of variables declaration//GEN-END:variables
}